export const foodDatabase = {
    breakfast: [
        { name: "Puttu (1 piece) + Kadala Curry (1 cup)", calories: 350, type: "veg", protein: 12, carbs: 60, fat: 5, ingredients: ["Rice Flour", "Coconut", "Chickpeas", "Onion", "Spices"] },
        { name: "Appam (2 pcs) + Vegetable Stew (1 cup)", calories: 320, type: "veg", protein: 6, carbs: 55, fat: 8, ingredients: ["Rice Flour", "Coconut Milk", "Carrot", "Beans", "Potato", "Spices"] },
        { name: "Idiyappam (3 pcs) + Egg Roast (1 egg)", calories: 300, type: "non-veg", protein: 10, carbs: 45, fat: 8, ingredients: ["Rice Flour", "Eggs", "Onion", "Tomato", "Spices"] },
        { name: "Dosa (2 pcs) + Sambar (1 cup)", calories: 300, type: "veg", protein: 8, carbs: 50, fat: 6, ingredients: ["Dosa Batter", "Toor Dal", "Mixed Vegetables", "Tamarind", "Spices"] },
        { name: "Idli (3 pcs) + Chutney (2 tbsp)", calories: 250, type: "veg", protein: 9, carbs: 48, fat: 2, ingredients: ["Idli Batter", "Coconut", "Green Chillies", "Mustard Seeds"] },
        { name: "Upma (1 cup) + Banana", calories: 320, type: "veg", protein: 6, carbs: 55, fat: 8, ingredients: ["Rava (Semolina)", "Onion", "Green Chillies", "Banana", "Spices"] },
        { name: "Oats Upma with Vegetables (1 cup)", calories: 280, type: "veg", protein: 10, carbs: 45, fat: 6, ingredients: ["Oats", "Mixed Vegetables", "Onion", "Spices"] },
        { name: "Ragi Puttu (1 piece) + Chickpea Curry", calories: 340, type: "veg", protein: 14, carbs: 58, fat: 5, ingredients: ["Ragi Flour", "Coconut", "Chickpeas", "Onion", "Spices"] },
        { name: "Pathiri (3 pcs) + Chicken Curry (Small portion)", calories: 400, type: "non-veg", protein: 20, carbs: 45, fat: 12, ingredients: ["Rice Flour", "Chicken", "Onion", "Tomato", "Coconut Milk", "Spices"] },
        { name: "Bread Omelette (2 slices + 2 eggs)", calories: 350, type: "non-veg", protein: 18, carbs: 30, fat: 15, ingredients: ["Bread", "Eggs", "Onion", "Pepper", "Oil"] },
    ],
    lunch: [
        { name: "Brown Rice (1 cup) + Fish Curry + Cabbage Thoran", calories: 450, type: "non-veg", protein: 25, carbs: 55, fat: 10, ingredients: ["Brown Rice", "Fish", "Coconut", "Cabbage", "Spices"] },
        { name: "White Rice (1 cup) + Moru Curry + Avial", calories: 400, type: "veg", protein: 8, carbs: 70, fat: 6, ingredients: ["Rice", "Curd", "Cucumber", "Mixed Vegetables", "Coconut", "Cumin"] },
        { name: "Chappalthi (2 pcs) + Chicken Roast + Salad", calories: 420, type: "non-veg", protein: 25, carbs: 40, fat: 12, ingredients: ["Atta (Wheat Flour)", "Chicken", "Onion", "Tomato", "Cucumber", "Spices"] },
        { name: "Rice (1 cup) + Sambar + Beans Mezhukkupuratti", calories: 380, type: "veg", protein: 10, carbs: 65, fat: 5, ingredients: ["Rice", "Toor Dal", "Mixed Vegetables", "Beans", "Spices", "Oil"] },
        { name: "Biryani Rice (Small portion) + Raita + Pickle", calories: 500, type: "veg", protein: 8, carbs: 75, fat: 15, ingredients: ["Basmati Rice", "Ghee", "Spices", "Curd", "Cucumber"] },
        { name: "Kanji (Rice Gruel) + Payar (Green Gram) Thoran", calories: 350, type: "veg", protein: 12, carbs: 65, fat: 2, ingredients: ["Rice", "Green Gram", "Coconut", "Garlic", "Chillies"] },
        { name: "Rice (1 cup) + Beef Fry (Small) + Cucumber Kichadi", calories: 550, type: "non-veg", protein: 25, carbs: 55, fat: 20, ingredients: ["Rice", "Beef", "Coconut Slices", "Spices", "Cucumber", "Curd"] },
        { name: "Wheat Porotta (2 pcs) + Vegetable Kurma", calories: 450, type: "veg", protein: 10, carbs: 60, fat: 15, ingredients: ["Wheat Flour", "Mixed Vegetables", "Coconut", "Cashews", "Spices"] },
        { name: "Curd Rice (1.5 cups) + Pickle", calories: 350, type: "veg", protein: 8, carbs: 50, fat: 10, ingredients: ["Rice", "Curd", "Milk", "Pomegranate (Optional)", "Pickle"] },
        { name: "Rice (1 cup) + Dal Curry + Fish Fry (1 pc)", calories: 480, type: "non-veg", protein: 22, carbs: 60, fat: 12, ingredients: ["Rice", "Toor/Moong Dal", "Fish", "Spices", "Oil"] },
    ],
    dinner: [
        { name: "Chappathi (2 pcs) + Green Gram Curry", calories: 300, type: "veg", protein: 12, carbs: 45, fat: 5, ingredients: ["Atta (Wheat Flour)", "Green Gram", "Onion", "Tomato", "Spices"] },
        { name: "Wheat Dosa (2 pcs) + Tomato Chutney", calories: 250, type: "veg", protein: 8, carbs: 45, fat: 4, ingredients: ["Wheat Flour", "Tomato", "Onion", "Red Chillies"] },
        { name: "Oats Porridge (Salted with veggies)", calories: 220, type: "veg", protein: 8, carbs: 35, fat: 4, ingredients: ["Oats", "Mixed Vegetables", "Milk/Water", "Spices"] },
        { name: "Grilled Fish + Salad (Cucumber, Onion, Tomato)", calories: 300, type: "non-veg", protein: 30, carbs: 10, fat: 12, ingredients: ["Fish", "Cucumber", "Onion", "Tomato", "Lemon", "Pepper"] },
        { name: "Chappathi (2 pcs) + Paneer Butter Masala (Light)", calories: 400, type: "veg", protein: 15, carbs: 40, fat: 18, ingredients: ["Atta (Wheat Flour)", "Paneer", "Tomato", "Cashews", "Butter (Light)", "Spices"] },
        { name: "Chicken Soup + Boiled Vegetables", calories: 250, type: "non-veg", protein: 20, carbs: 15, fat: 8, ingredients: ["Chicken", "Carrot", "Beans", "Pepper", "Ginger", "Garlic"] },
        { name: "Puttu (1 piece) + Steamed Banana", calories: 280, type: "veg", protein: 4, carbs: 60, fat: 1, ingredients: ["Rice Flour", "Coconut", "Banana"] },
        { name: "Scrambled Eggs (2) + Toast (1 slice)", calories: 280, type: "non-veg", protein: 16, carbs: 15, fat: 15, ingredients: ["Eggs", "Bread", "Butter", "Pepper"] },
        { name: "Multigrain Roti (2 pcs) + Baingan Bharta", calories: 320, type: "veg", protein: 8, carbs: 50, fat: 8, ingredients: ["Multigrain Atta", "Eggplant (Baingan)", "Onion", "Tomato", "Spices"] },
        { name: "Fruit Bowl (Papaya, Melon, Apple)", calories: 200, type: "veg", protein: 2, carbs: 50, fat: 1, ingredients: ["Papaya", "Watermelon", "Apple"] },
    ],
    snacks: [
        { name: "Green Tea + Roasted Peanuts (Small handful)", calories: 150, type: "veg", protein: 6, carbs: 5, fat: 12, ingredients: ["Green Tea Bags", "Peanuts"] },
        { name: "Black Coffee + 2 Marie Biscuits", calories: 80, type: "veg", protein: 1, carbs: 15, fat: 2, ingredients: ["Coffee Powder", "Marie Biscuits"] },
        { name: "Banana (Small)", calories: 90, type: "veg", protein: 1, carbs: 23, fat: 0, ingredients: ["Banana"] },
        { name: "Buttermilk (Sambharam)", calories: 50, type: "veg", protein: 2, carbs: 5, fat: 1, ingredients: ["Curd", "Green Chillies", "Ginger", "Curry Leaves"] },
        { name: "Boiled Egg Whites (2)", calories: 34, type: "non-veg", protein: 7, carbs: 0, fat: 0, ingredients: ["Eggs"] },
        { name: "Sprouts Salad (1 cup)", calories: 120, type: "veg", protein: 8, carbs: 18, fat: 1, ingredients: ["Green Gram Sprouts", "Onion", "Tomato", "Lemon"] },
        { name: "Unniyappam (1 small - occasional treat)", calories: 150, type: "veg", protein: 2, carbs: 25, fat: 6, ingredients: ["Rice Flour", "Jaggery", "Banana", "Coconut", "Oil"] },
        { name: "Parippu Vada (1 small - occasional treat)", calories: 180, type: "veg", protein: 6, carbs: 20, fat: 10, ingredients: ["Chana Dal", "Onion", "Dry Red Chillies", "Curry Leaves", "Oil"] },
        { name: "Sundal (Chickpea salad) (1/2 cup)", calories: 140, type: "veg", protein: 7, carbs: 20, fat: 3, ingredients: ["Chickpeas", "Coconut", "Mustard Seeds", "Curry Leaves"] },
        { name: "Handful of Almonds/Walnuts", calories: 160, type: "veg", protein: 6, carbs: 6, fat: 14, ingredients: ["Almonds", "Walnuts"] },
    ]
};
